version: '3'
services:
  api:
    container_name: api
    build: ./
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=myapp
      - FLASK_ENV=development
      - FLASK_APP=app.py
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    external: true
